[project]
name = 'Blockchain-Based-Specialized-Tool-Fabrication-for-Disabilities'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.design-registration]
path = 'contracts/design-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.effectiveness-feedback]
path = 'contracts/effectiveness-feedback.clar'
clarity_version = 2
epoch = 2.5

[contracts.fabricator-matching]
path = 'contracts/fabricator-matching.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-sourcing]
path = 'contracts/material-sourcing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
